Layout/LineLength:
  Max: 100
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  Enabled: true

Style/CollectionMethods:
  Description: 'Preferred collection methods.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size'
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

# RuboCop RSpec

RSpec/ExpectChange:
  EnforcedStyle: method_call
  Enabled: true
